/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.Scanner;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import dao.IOAcceso;
import modelo.Libro;
import sort.*;
import search.*;


public class Vista extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    static Libro[] libros;
    static Libro[] libroOrdenado;

    /**
     * Creates new form Vista
     */
    public Vista() {

        initComponents();

        Color color = new Color(43, 43, 43);

        jScrollPane1.getViewport().setBackground(color);
        JTableHeader headerUno = tablaUno.getTableHeader();
        headerUno.setBackground(Color.white);
        headerUno.setForeground(Color.black);

        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnUnidad5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnUnidad6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnReload = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUno = new javax.swing.JTable();
        barra = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLinear = new javax.swing.JButton();
        btnBynary = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblLinear = new javax.swing.JLabel();
        lblBinary = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBurbuja = new javax.swing.JButton();
        btnSeleccion = new javax.swing.JButton();
        btnQuick = new javax.swing.JButton();
        btnMerge = new javax.swing.JButton();
        btnShell = new javax.swing.JButton();
        lblSeleccion = new javax.swing.JLabel();
        lblQuick = new javax.swing.JLabel();
        lblBurbuja1 = new javax.swing.JLabel();
        lblMerge = new javax.swing.JLabel();
        lblShell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(22, 21, 22));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 21, 22));

        btnUnidad5.setBackground(new java.awt.Color(31, 223, 100));
        btnUnidad5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUnidad5.setText("UNIDAD 5");
        btnUnidad5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUnidad5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUnidad5MouseExited(evt);
            }
        });
        btnUnidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidad5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ORDENACION");

        btnUnidad6.setBackground(new java.awt.Color(31, 223, 100));
        btnUnidad6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUnidad6.setText("UNIDAD 6");
        btnUnidad6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidad6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUnidad6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUnidad6MouseExited(evt);
            }
        });
        btnUnidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidad6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Y BUSQUEDA");

        btnReload.setBackground(new java.awt.Color(31, 223, 100));
        btnReload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReload.setText("RESTAURAR DATOS");
        btnReload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReloadMouseExited(evt);
            }
        });
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        panel1.setBackground(new java.awt.Color(24, 24, 24));

        jScrollPane1.setBackground(new java.awt.Color(255, 0, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setWheelScrollingEnabled(false);

        tablaUno.setBackground(new java.awt.Color(43, 43, 43));
        tablaUno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaUno.setForeground(new java.awt.Color(255, 255, 255));
        tablaUno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo", "Autor", "Editorial", "Edicion", "Idioma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaUno.setSelectionBackground(new java.awt.Color(31, 223, 100));
        tablaUno.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablaUno.getTableHeader().setResizingAllowed(false);
        tablaUno.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaUno);
        if (tablaUno.getColumnModel().getColumnCount() > 0) {
            tablaUno.getColumnModel().getColumn(0).setResizable(false);
            tablaUno.getColumnModel().getColumn(1).setResizable(false);
            tablaUno.getColumnModel().getColumn(2).setResizable(false);
            tablaUno.getColumnModel().getColumn(3).setResizable(false);
            tablaUno.getColumnModel().getColumn(4).setResizable(false);
            tablaUno.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        fondo.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 790, 630));

        barra.setBackground(new java.awt.Color(22, 21, 22));

        btnSalir.setBackground(new java.awt.Color(31, 223, 100));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("x");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 240, 30));

        jPanel3.setBackground(new java.awt.Color(22, 21, 22));

        btnLinear.setBackground(new java.awt.Color(31, 223, 100));
        btnLinear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLinear.setForeground(new java.awt.Color(255, 255, 255));
        btnLinear.setText("LINEAR-SEARCH( )");
        btnLinear.setContentAreaFilled(false);
        btnLinear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLinear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLinearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLinearMouseExited(evt);
            }
        });
        btnLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinearActionPerformed(evt);
            }
        });

        btnBynary.setBackground(new java.awt.Color(31, 223, 100));
        btnBynary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBynary.setForeground(new java.awt.Color(255, 255, 255));
        btnBynary.setText("BINARY-SEARCH( )");
        btnBynary.setContentAreaFilled(false);
        btnBynary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBynary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBynaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBynaryMouseExited(evt);
            }
        });
        btnBynary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBynaryActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ISBN");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setSelectionColor(new java.awt.Color(31, 223, 100));

        lblLinear.setForeground(new java.awt.Color(255, 255, 255));

        lblBinary.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBynary, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(btnLinear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBynary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 230, 590));

        jPanel2.setBackground(new java.awt.Color(22, 21, 22));

        btnBurbuja.setBackground(new java.awt.Color(31, 223, 100));
        btnBurbuja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBurbuja.setForeground(new java.awt.Color(255, 255, 255));
        btnBurbuja.setText("BURBUJA( )");
        btnBurbuja.setContentAreaFilled(false);
        btnBurbuja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBurbuja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBurbujaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBurbujaMouseExited(evt);
            }
        });
        btnBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurbujaActionPerformed(evt);
            }
        });

        btnSeleccion.setBackground(new java.awt.Color(31, 223, 100));
        btnSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccion.setText("SELECCION( )");
        btnSeleccion.setContentAreaFilled(false);
        btnSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSeleccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeleccionMouseExited(evt);
            }
        });
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });

        btnQuick.setBackground(new java.awt.Color(31, 223, 100));
        btnQuick.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuick.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick.setText("QUICK-SORT( )");
        btnQuick.setContentAreaFilled(false);
        btnQuick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuickMouseExited(evt);
            }
        });
        btnQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickActionPerformed(evt);
            }
        });

        btnMerge.setBackground(new java.awt.Color(31, 223, 100));
        btnMerge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMerge.setForeground(new java.awt.Color(255, 255, 255));
        btnMerge.setText("MERGE-SORT( )");
        btnMerge.setContentAreaFilled(false);
        btnMerge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMerge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMergeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMergeMouseExited(evt);
            }
        });
        btnMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeActionPerformed(evt);
            }
        });

        btnShell.setBackground(new java.awt.Color(31, 223, 100));
        btnShell.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnShell.setForeground(new java.awt.Color(255, 255, 255));
        btnShell.setText("SHELL-SORT( )");
        btnShell.setContentAreaFilled(false);
        btnShell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShellMouseExited(evt);
            }
        });
        btnShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShellActionPerformed(evt);
            }
        });

        lblSeleccion.setForeground(new java.awt.Color(255, 255, 255));

        lblQuick.setForeground(new java.awt.Color(255, 255, 255));

        lblBurbuja1.setForeground(new java.awt.Color(255, 255, 255));

        lblMerge.setForeground(new java.awt.Color(255, 255, 255));

        lblShell.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShell, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBurbuja1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblShell, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBurbuja1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(btnSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuick, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(btnMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMerge, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(btnShell, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShell, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 230, 590));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnUnidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidad5ActionPerformed
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_btnUnidad5ActionPerformed

    private void btnUnidad5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad5MouseEntered
        btnUnidad5.setBackground(Color.white);
    }//GEN-LAST:event_btnUnidad5MouseEntered

    private void btnUnidad5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad5MouseExited
        Color color = new Color(31, 223, 100);
        btnUnidad5.setBackground(color);
    }//GEN-LAST:event_btnUnidad5MouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        Color color = new Color(31, 223, 100);
        btnSalir.setForeground(color);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnUnidad6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad6MouseEntered
        btnUnidad6.setBackground(Color.white);
    }//GEN-LAST:event_btnUnidad6MouseEntered

    private void btnUnidad6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidad6MouseExited
        Color color = new Color(31, 223, 100);
        btnUnidad6.setBackground(color);
    }//GEN-LAST:event_btnUnidad6MouseExited

    private void btnUnidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidad6ActionPerformed
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_btnUnidad6ActionPerformed

    private void btnBurbujaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBurbujaMouseEntered
        Color color = new Color(31, 223, 100);
        btnBurbuja.setForeground(color);
    }//GEN-LAST:event_btnBurbujaMouseEntered

    private void btnBurbujaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBurbujaMouseExited
        btnBurbuja.setForeground(Color.white);
    }//GEN-LAST:event_btnBurbujaMouseExited

    private void btnBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurbujaActionPerformed
        Libro[] librosAux = libros.clone();
        MetodoBurbuja metodoBurbuja = new MetodoBurbuja();
        long startTime = System.currentTimeMillis();
        metodoBurbuja.metodoBurbuja(librosAux);
        long endTime = System.currentTimeMillis();
        long totalTime = endTime - startTime;
        lblBurbuja1.setText(totalTime + " millisegundos");
        librosOrdenados(librosAux);
    }//GEN-LAST:event_btnBurbujaActionPerformed

    private void btnSeleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionMouseEntered
        Color color = new Color(31, 223, 100);
        btnSeleccion.setForeground(color);
    }//GEN-LAST:event_btnSeleccionMouseEntered

    private void btnSeleccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionMouseExited
        btnSeleccion.setForeground(Color.white);
    }//GEN-LAST:event_btnSeleccionMouseExited

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        Libro[] librosAux = libros.clone();
        SelectionSort selectionSort = new SelectionSort();
        long startTime = System.currentTimeMillis();

        selectionSort.selectionSort(librosAux);

        long endTime = System.currentTimeMillis();
        long totalTime = endTime - startTime;
        lblSeleccion.setText(totalTime + " millisegundos");
        librosOrdenados(librosAux);
    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void btnQuickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuickMouseEntered
        Color color = new Color(31, 223, 100);
        btnQuick.setForeground(color);
    }//GEN-LAST:event_btnQuickMouseEntered

    private void btnQuickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuickMouseExited
        btnQuick.setForeground(Color.white);
    }//GEN-LAST:event_btnQuickMouseExited

    private void btnQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickActionPerformed
        Libro[] librosAux = libros.clone();
        int n = libros.length;
        QuickSort quickSort = new QuickSort();
        long startTime = System.currentTimeMillis();

        librosAux = quickSort.sort(librosAux, 0, n - 1);

        long endTime = System.currentTimeMillis();
        long totalTime = endTime - startTime;
        lblQuick.setText(totalTime + " millisegundos");
        librosOrdenados(librosAux);
    }//GEN-LAST:event_btnQuickActionPerformed

    private void btnMergeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMergeMouseEntered
        Color color = new Color(31, 223, 100);
        btnMerge.setForeground(color);
    }//GEN-LAST:event_btnMergeMouseEntered

    private void btnMergeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMergeMouseExited
        btnMerge.setForeground(Color.white);
    }//GEN-LAST:event_btnMergeMouseExited

    private void btnMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeActionPerformed
        Libro[] librosAux = libros.clone();
        MergeSort mergeSort = new MergeSort();
        long startTime = System.currentTimeMillis();

        librosAux = mergeSort.mergeSort(librosAux);

        long endTime = System.currentTimeMillis();
        long totalTime = endTime - startTime;
        lblMerge.setText(totalTime + " millisegundos");
        librosOrdenados(librosAux);
    }//GEN-LAST:event_btnMergeActionPerformed

    private void btnShellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShellMouseEntered
        Color color = new Color(31, 223, 100);
        btnShell.setForeground(color);
    }//GEN-LAST:event_btnShellMouseEntered

    private void btnShellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShellMouseExited
        btnShell.setForeground(Color.white);
    }//GEN-LAST:event_btnShellMouseExited

    private void btnShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShellActionPerformed
        Libro[] librosAux = libros.clone();
        ShellSort shellSort = new ShellSort();
        long startTime = System.currentTimeMillis();

        librosAux = shellSort.sort(librosAux);

        long endTime = System.currentTimeMillis();
        long totalTime = endTime - startTime;
        lblShell.setText(totalTime + " millisegundos");
        librosOrdenados(librosAux);
    }//GEN-LAST:event_btnShellActionPerformed

    private void btnLinearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinearMouseEntered
        Color color = new Color(31, 223, 100);
        btnLinear.setForeground(color);
    }//GEN-LAST:event_btnLinearMouseEntered

    private void btnLinearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinearMouseExited
        btnLinear.setForeground(Color.white);
    }//GEN-LAST:event_btnLinearMouseExited

    private void btnLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinearActionPerformed
        if (jTextField1.getText() == "") {
            JOptionPane.showMessageDialog(null, "Ingrese un ISBN", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
        } else {
            LinearSearch linearSearch = new LinearSearch();
            String isbn = jTextField1.getText();
            long startTime = System.nanoTime();

            int res = linearSearch.linearSearch(libros, isbn);

            long endTime = System.nanoTime();
            long totalTime = endTime - startTime;
            lblLinear.setText(totalTime + " nanoTime");
            if (res != -1) {
                libroConsulta(libros, res);
            } else {
                JOptionPane.showMessageDialog(null, "Elemento no encontrado", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLinearActionPerformed

    private void btnBynaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBynaryMouseEntered
        Color color = new Color(31, 223, 100);
        btnBynary.setForeground(color);
    }//GEN-LAST:event_btnBynaryMouseEntered

    private void btnBynaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBynaryMouseExited
        btnBynary.setForeground(Color.white);
    }//GEN-LAST:event_btnBynaryMouseExited

    private void btnBynaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBynaryActionPerformed
        if (jTextField1.getText() == "") {
            JOptionPane.showMessageDialog(null, "Ingrese un ISBN", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
        } else {
            String isbn = jTextField1.getText();
            long startTime = System.nanoTime();

            BinarySearch binarySearch = new BinarySearch();

            long endTime = System.nanoTime();
            long totalTime = endTime - startTime;
            lblBinary.setText(totalTime + " nanoTime");
            Libro[] aux = libroOrdenado.clone();
            int i = binarySearch.bSearch(aux, isbn);
            if (i != -1) {
                libroConsulta(aux, i);
            } else {
                JOptionPane.showMessageDialog(null, "Elemento no encontrado", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBynaryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            libros = IOAcceso.readFromFile("recursos/libros");
            if (libros == null) {
                JOptionPane.showMessageDialog(null, "No hay datos en el archivo");
            }
            libroOrdenado = libros.clone();
            int n = libroOrdenado.length;
            QuickSort quickSort = new QuickSort();
            libroOrdenado = quickSort.sortIsbn(libroOrdenado, 0, n - 1);
            actualizarLibros();
        } catch (FileNotFoundException e1) {
            JOptionPane.showMessageDialog(null, "Error de acceso al archivo");
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (libros != null) {
            try {
                IOAcceso.writeToFile(libros);
            } catch (FileNotFoundException e1) {
                JOptionPane.showMessageDialog(null, "Error de acceso al archivo de salida");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos que guardar al archivo");
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnReloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseEntered
        btnReload.setBackground(Color.white);
    }//GEN-LAST:event_btnReloadMouseEntered

    private void btnReloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseExited
        Color color = new Color(31, 223, 100);
        btnReload.setBackground(color);
    }//GEN-LAST:event_btnReloadMouseExited

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        actualizarLibros();
    }//GEN-LAST:event_btnReloadActionPerformed

    public void actualizarLibros() {
        Object[] datos = new Object[tablaUno.getColumnCount()];
        DefaultTableModel modelo = (DefaultTableModel) tablaUno.getModel();
        modelo.setRowCount(0);
        String infoLibros = "";
        Libro[] librosInfo = libros.clone();
        int i = 0;
        while (i < libros.length) {
            infoLibros += librosInfo[i].toString() + "\n";
            i++;
        }
        String datosEntrada = infoLibros;
        try (Scanner entrada = new Scanner(datosEntrada)) {
            while (entrada.hasNext()) {
                String datosPrestamo = entrada.nextLine();
                String[] subcadenas = datosPrestamo.split("\t");
                datos[0] = subcadenas[0];
                datos[1] = subcadenas[1];
                datos[2] = subcadenas[2];
                datos[3] = subcadenas[3];
                datos[4] = subcadenas[4];
                datos[5] = subcadenas[5];
                modelo.addRow(datos);
            }
        }
    }

    public void librosOrdenados(Libro[] librosInfo) {
        Object[] datos = new Object[tablaUno.getColumnCount()];
        DefaultTableModel modelo = (DefaultTableModel) tablaUno.getModel();
        modelo.setRowCount(0);
        String infoLibros = "";
        int i = 0;
        while (i < libros.length) {
            infoLibros += librosInfo[i].toString() + "\n";
            i++;
        }
        String datosEntrada = infoLibros;
        try (Scanner entrada = new Scanner(datosEntrada)) {
            while (entrada.hasNext()) {
                String datosPrestamo = entrada.nextLine();
                String[] subcadenas = datosPrestamo.split("\t");
                datos[0] = subcadenas[0];
                datos[1] = subcadenas[1];
                datos[2] = subcadenas[2];
                datos[3] = subcadenas[3];
                datos[4] = subcadenas[4];
                datos[5] = subcadenas[5];
                modelo.addRow(datos);
            }
        }
    }

    public void libroConsulta(Libro[] libros, int pos) {
        Object[] datos = new Object[tablaUno.getColumnCount()];
        DefaultTableModel modelo = (DefaultTableModel) tablaUno.getModel();
        modelo.setRowCount(0);
        String infoLibros = "";
        infoLibros += libros[pos].toString();
        String datosEntrada = infoLibros;
        try (Scanner entrada = new Scanner(datosEntrada)) {
            while (entrada.hasNext()) {
                String datosPrestamo = entrada.nextLine();
                String[] subcadenas = datosPrestamo.split("\t");
                datos[0] = subcadenas[0];
                datos[1] = subcadenas[1];
                datos[2] = subcadenas[2];
                datos[3] = subcadenas[3];
                datos[4] = subcadenas[4];
                datos[5] = subcadenas[5];
                modelo.addRow(datos);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JButton btnBurbuja;
    private javax.swing.JButton btnBynary;
    private javax.swing.JButton btnLinear;
    private javax.swing.JButton btnMerge;
    private javax.swing.JButton btnQuick;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JButton btnShell;
    private javax.swing.JButton btnUnidad5;
    private javax.swing.JButton btnUnidad6;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBinary;
    private javax.swing.JLabel lblBurbuja1;
    private javax.swing.JLabel lblLinear;
    private javax.swing.JLabel lblMerge;
    private javax.swing.JLabel lblQuick;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblShell;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tablaUno;
    // End of variables declaration//GEN-END:variables
}
